source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReadMoreTableViewController_Example', :exclusive => true do
  pod "ReadMoreTableViewController", :path => "../"
end

target 'ReadMoreTableViewController_Tests', :exclusive => true do
  pod "ReadMoreTableViewController", :path => "../"
end
