source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'LoadMoreTableViewController_Example' do
  pod "LoadMoreTableViewController", :path => "../"
end

target 'LoadMoreTableViewController_Tests' do
  pod "LoadMoreTableViewController", :path => "../"
end

# cf. http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.3'
        end
    end
end
